Water tank fixes and staples crafting
HippieStationArchive/HippieStation13-2 pull request #131
Opened 2017-02-10 16:50 UTC by tortellinitony

:cl:
add: You can remove the top from a water tank and put chemicals in it
fix: You can craft staples
add: New tank sprites
/:cl:

https://vgy.me/odfQJI.png

2017-02-10 17:13 UTC, JohnGinnane commented
Don't forget to put your name after the first CL

2017-02-10 17:19 UTC, JohnGinnane requested changes

2017-02-10 17:19 UTC, JohnGinnane commented on code/modules/reagents/reagent_dispenser.dm
> +			src.container_type = OPENCONTAINER
Might be better to do `container_type |= OPENCONTAINER`

2017-02-10 17:19 UTC, JohnGinnane commented on code/modules/reagents/reagent_dispenser.dm
> +			src.container_type = null
And then `container_type &= ~OPENCONTAINER` here

2017-02-10 18:00 UTC, KittyKathy commented
So does this only work for water tanks? what about welding tanks, high capacity water tanks that botany gets and chemical tanks from atmos does tg even have chemical tanks though? I know pre rebase had it but that was rarely used.

2017-02-10 18:37 UTC, tortellinitony commented
This only works for water tanks, and tg does not even have chemical tanks.

2017-02-11 05:05 UTC, KittyKathy commented
Why not make it work for all of them besides the problem of only the water tank having a sprite. I don't think they had a sprite pre rebase though did they?.

2017-02-11 14:23 UTC, j-mie approved these changes

2017-02-11 14:23 UTC, merged