Freon tanks and adds them to dispensers
HippieStationArchive/HippieStation13-2 pull request #175
Opened 2017-02-12 19:16 UTC by tortellinitony

:cl: Tortellini Tony
add: Adds freon tanks and puts them inside some tank dispensers
/:cl:

Also recompiled tgui which fixed the cryo UI as well.

2017-02-12 23:06 UTC, ghost requested changes

2017-02-12 23:06 UTC, BTFO commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +	desc = "Contains dangerous plasma. Do not inhale. Warning: extremely flammable."
You had one job

2017-02-12 23:06 UTC, BTFO commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +	air_contents.temperature = 120
freon needs to be cold, not hot

2017-02-12 23:08 UTC, JamieH commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +	air_contents.temperature = 120
Isn't Byond temperature in kelvin? So that'd be `-153.15C`

2017-02-12 23:16 UTC, JamieH commented
@BTFO Not really relevant to this issue but you were banned for ban evasion ingame right? Ping me on our Discord: https://discord.gg/ncTbx

2017-02-12 23:20 UTC, j-mie approved these changes

2017-02-12 23:21 UTC, j-mie approved these changes

2017-02-12 23:21 UTC, merged

2017-02-13 10:54 UTC, BTFO commented
@JamieH I was indeed banned by someone for alledged ban evasion, i however never evaded a single ban and have not been banned before, I'll see if i can get on the discord once i get back from work

2017-02-13 11:54 UTC, JamieH commented
@BTFO Alright cool, Once you're on ping me and we'll see what we can do about ban, I've sent a new Discord link with 12 hour expiry https://discord.gg/7797q (Ping me if that doesn't work)