Makes teleporters respect exile implants and gives them to hotel staff
HippieStationArchive/HippieStation13-2 pull request #180
Opened 2017-02-13 01:43 UTC by cacogen

:cl: cacogen
add: Hotel staff now have exile implants
tweak: Teleporters now respect exile implants
/:cl:

2017-02-13 10:51 UTC, ghost requested changes

2017-02-13 10:51 UTC, BTFO commented on code/game/machinery/teleporter.dm
> +			AM << "\black [src] has detected your implant and is blocking your entry."
Please use spanclasses

2017-02-13 10:51 UTC, BTFO commented on code/game/objects/effects/portals.dm
> +			AM << "\black [src] has detected your implant and is blocking your entry."
Please use spanclasses

2017-02-13 10:51 UTC, BTFO commented on code/game/objects/effects/portals.dm
> +/obj/effect/portal/proc/blockExiles(atom/movable/AM)
This check is bad - players can simply go into a locker or something else to avoid this

2017-02-13 10:51 UTC, BTFO commented on code/game/machinery/teleporter.dm
> +/obj/machinery/teleport/hub/proc/blockExiles(atom/movable/AM)
This check is bad - players can simply go into a locker or something else to avoid this

2017-02-13 10:51 UTC, BTFO commented on code/game/objects/effects/portals.dm
> +/obj/effect/portal/proc/blockExiles(atom/movable/AM)
The duplication of this check is also bad, don't duplicate this create a generic proc in helpers.dm

2017-02-13 10:51 UTC, BTFO commented on code/game/machinery/teleporter.dm
> +			AM << "\black [src] has detected your implant and is blocking your entry."
The duplication of this check is also bad, don't duplicate this create a generic proc in helpers.dm

2017-02-13 19:25 UTC, cacogen commented on code/game/objects/effects/portals.dm
> +/obj/effect/portal/proc/blockExiles(atom/movable/AM)
what should it check instead

2017-02-13 19:26 UTC, tortellinitony commented on code/game/objects/effects/portals.dm
> +/obj/effect/portal/proc/blockExiles(atom/movable/AM)
make it run the check on mobs if they are in the contents of an object that passes through?

2017-02-13 20:09 UTC, cacogen commented on code/game/objects/effects/portals.dm
> +			AM << "\black [src] has detected your implant and is blocking your entry."
code was already like that, but okay

2017-02-13 21:04 UTC, cacogen commented on code/game/objects/effects/portals.dm
> +/obj/effect/portal/proc/blockExiles(atom/movable/AM)
can't figure this out
```
/proc/blockExiles(atom/movable/AM, obj/T)
	if(T.z == ZLEVEL_STATION) //exiles can enter teleporters on the station
		return FALSE
	if(istype(T, /obj/machinery/teleport/hub))
		var/obj/machinery/teleport/hub/H = T
		if(H.com.target.z == z) //exiles can enter hubs that keep them on the zlevel
			return FALSE
	if(istype(T, /obj/effect/portal)) //exiles can enter portals that keep them on the zlevel
		var/obj/effect/portal/P = T
		if(P.target.z == z)
			return FALSE
	if(istype(AM, /mob/living/carbon))
		var/mob/living/carbon/C = AM
		for(var/obj/item/weapon/implant/exile/E in C.implants)//Checking that there is an exile implant
			AM << "\black [src] has detected your implant and is blocking your entry."
			return TRUE
	if(AM.contents)
		for(var/mob/living/carbon/C in AM.contents)
			for(var/obj/item/weapon/implant/exile/E in C.implants)
				C << "\black [src] has detected your implant and is blocking your entry."
				return TRUE
```
```
loading tgstation.dme
loading interface\skin.dmf
code\__HELPERS\unsorted.dm:1345:error: z: undefined var
code\__HELPERS\unsorted.dm:1349:error: z: undefined var
code\__HELPERS\unsorted.dm:1345:error: H.com.target.z: undefined var
code\__HELPERS\unsorted.dm:1344:warning: H: variable defined but not used
tgstation.dmb - 3 errors, 1 warning (2/14/17 9:59 am)
```

2017-02-13 21:59 UTC, KittyKathy commented
There might be a easier way to do this I will see if I can help.

2017-02-13 22:38 UTC, cacogen commented
hopefully one of the people who had a problem with the code will say what i'm doing wrong in the code i posted so i can fix it

otherwise ¯\_(ツ)_/¯

2017-02-14 06:24 UTC, cacogen commented
tortilla tony is gay lmao

2017-02-14 09:21 UTC, cacogen commented
because i prefer this method to tortoise tom's

if his gets pulled i'll just change this to a general exile implant buff instead

2017-02-14 09:32 UTC, Chnkr commented
```
/proc/get_hiding_jerk(var/A)
	for(var/atom/AT in A)
		if(AT.contents.len)
                    get_hiding_jerk(AT)
		if(ismob(AM))
			var/mob/M = AM
			M.gib()
```

This is all you need to get fuckers hiding in other things, technically this should work. maybe you need to do something similar, but you get the idea

might need to shove a `CHECK_TICK` in there as well

2017-02-14 09:44 UTC, Chnkr commented on code/game/machinery/teleporter.dm
> +				spawn(30)
NO.

SPAWNS ARE BAD IN HERE, USE ADDTIMER.

2017-02-14 09:44 UTC, Chnkr commented on code/game/objects/effects/portals.dm
> +				spawn(30)
NO.

SPAWNS ARE BAD IN HERE, USE ADDTIMER.

2017-02-14 10:14 UTC, cacogen commented on code/game/machinery/teleporter.dm
> +				spawn(30)
okay. why are spawns a problem?

2017-02-14 21:50 UTC, cacogen commented on code/game/machinery/teleporter.dm
> +				spawn(30)
i tried using addtimer here but that garbage wouldn't work after at least an hour of troubleshooting so i ended up getting rid of the message completely

2017-02-14 21:51 UTC, cacogen commented on code/game/machinery/teleporter.dm
> +				spawn(30)
i.e. fuck that shit

2017-02-16 12:33 UTC, banthebantz commented
Meh I'd just have the scum autogib if they enter another z level

2017-02-16 12:48 UTC, Chnkr commented
This PR is redunant now that we have the NOTP mutation

2017-02-18 02:06 UTC, cacogen commented
i'm gonna close this for now because i no longer care about it and timmy turner's pr makes this redundant in its current form

2017-02-18 02:06 UTC, closed without merging