REVERTS GENETICS NERFS ELECTRIC BOOGALOO
HippieStationArchive/HippieStation13-2 pull request #204
Opened 2017-02-14 22:45 UTC by banthebantz

WAS MERGED IN THE FIRST REBASE, REVERTS THESE BIG FUCKING NERFS OK

2017-02-14 22:48 UTC, ghost requested changes

2017-02-14 22:48 UTC, Chnkr commented on code/modules/mob/living/ventcrawling.dm
> +			if(iscarbon(src) && contents.len && ventcrawler < 2)//It must have atleast been 1 to get this far
I don't see why this would require a change, mind explaining why this entire check was altered?

2017-02-14 22:48 UTC, Chnkr commented on html/changelogs/Banthebantz - Genetics revert.yml
> +################################
Changelogs are now in the PR body, please use that

2017-02-14 22:48 UTC, Chnkr commented on code/_onclick/telekinesis.dm
> -		user.changeNext_move(CLICK_CD_MELEE)
I'd suggest putting the click delay back, unless there is a very good reason to remove it

2017-02-14 22:50 UTC, banthebantz commented on code/_onclick/telekinesis.dm
> -		user.changeNext_move(CLICK_CD_MELEE)
The click delay was the the main nerf along with the inability to sustain a grab on items that have been picked up, with click delay it's just like normal throwing

2017-02-14 22:50 UTC, banthebantz commented on html/changelogs/Banthebantz - Genetics revert.yml
> +################################
wah?

2017-02-14 22:50 UTC, banthebantz commented on code/modules/mob/living/ventcrawling.dm
> +			if(iscarbon(src) && contents.len && ventcrawler < 2)//It must have atleast been 1 to get this far
I just changed it to how it was pre-rebase fam

2017-02-14 23:00 UTC, tortellinitony commented on code/_onclick/telekinesis.dm
> -		user.changeNext_move(CLICK_CD_MELEE)
Or maybe it's not a "nerf" and is there for a reason?

Please link to the /tg/ PR that this reverts if you can find it.

2017-02-15 10:54 UTC, Chnkr commented on code/modules/mob/living/ventcrawling.dm
> +			if(iscarbon(src) && contents.len && ventcrawler < 2)//It must have atleast been 1 to get this far
There is no need to change this check tho

2017-02-15 14:35 UTC, Carbonhell commented on code/_onclick/telekinesis.dm
> -		user.changeNext_move(CLICK_CD_MELEE)
I'm against removing the click delay. If you want you can lower it though, https://github.com/HippieStation/HippieStation13/blob/42915e2f0fc726df31f1cebd7f3206907862c391/code/__DEFINES/combat.dm#L49
I'd suggest CLICK_CD_RANGE or CLICK_CD_RAPID

2017-02-15 14:36 UTC, Carbonhell commented on html/changelogs/Banthebantz - Genetics revert.yml
> +################################
The CL stuff in your PR first comment, a bot will make a changelog based on what's between Cl and /Cl so you don't need to make the yml files anymore

2017-02-15 14:42 UTC, Chnkr commented on code/_onclick/telekinesis.dm
> -		user.changeNext_move(CLICK_CD_MELEE)
`CLICK_CD_RAPID / 2`

2017-02-15 18:27 UTC, banthebantz commented on code/modules/mob/living/ventcrawling.dm
> +			if(iscarbon(src) && contents.len && ventcrawler < 2)//It must have atleast been 1 to get this far
Woops I was under the assumption that TG ventcrawling was still broken like it was in the last rebase so I neglected to check.

2017-02-16 05:40 UTC, j-mie approved these changes

2017-02-16 05:41 UTC, merged