Adds the cargo transporter
HippieStationArchive/HippieStation13-2 pull request #230
Opened 2017-02-17 09:35 UTC by JamieH

:cl: JamieH
add: Added new things
add: Added more things
/:cl:

Adds in a cargo transporter, inspiration/some code from Goon.

Cargo Telepads are located at:
- Cargo Bay
- Engineering
- Medbay
- Research
- Mining Output

Look here: https://share.jamiehankins.co.uk/ShareX/2017/02/2017-02-17_09-05-38.mp4
(I fixed the bug at the end)

2017-02-17 09:36 UTC, McBawbaggings commented
Dirty branch. Otherwise the RCS was a good feature back from pre-pre-rebase. +1

2017-02-17 09:47 UTC, ghost requested changes

2017-02-17 09:47 UTC, Chnkr commented on code/game/objects/structures/crates_lockers/closets.dm
> +		W:cargoteleport(src, user)
**NO**

**_DO NOT USE THE COLON CHARACTER_**

2017-02-17 09:47 UTC, Chnkr commented on code/modules/atmospherics/machinery/portable/canister.dm
> +		W:cargoteleport(src, user)
**NO**

**_DO NOT USE THE COLON CHARACTER_**

2017-02-17 09:47 UTC, Chnkr commented on code/modules/mining/satchel_ore_boxdm.dm
> +		W:cargoteleport(src, user)
**NO**

**_DO NOT USE THE COLON CHARACTER_**

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +var/global/list/cargopads = list() // Global List of Cargo Pads
Put this in `code/_globalvars`

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
>  /obj/machinery/telepad_cargo
Create a new telepad object and put it in the hippiestation module, please leave the current code unchanged for the sake of easier upstream merges

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +	var/active = 0
`FALSE`

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
>  	anchored = 1
`TRUE`

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
>  	use_power = 1
`TRUE`

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
>  	var/stage = 0
No magic numbers please

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +	if (active && !cargopads.Find(src))
Please use the list helpers when accessing lists, `Find` is rather slow and there are better solutions as seen here: https://github.com/tgstation/tgstation/blob/c30d07f55a1078b6463b56046884fbce9bac6959/code/__HELPERS/lists.dm

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +		cargopads.Add(src)
Please use the list helpers when accessing lists, `Add` is rather slow and there are better solutions as seen here: https://github.com/tgstation/tgstation/blob/c30d07f55a1078b6463b56046884fbce9bac6959/code/__HELPERS/lists.dm

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +	if (cargopads.Find(src))
Please use the list helpers when accessing lists, `Find` is rather slow and there are better solutions as seen here: https://github.com/tgstation/tgstation/blob/c30d07f55a1078b6463b56046884fbce9bac6959/code/__HELPERS/lists.dm

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +		cargopads.Remove(src)
Please use the list helpers when accessing lists, `Remove` is rather slow and there are better solutions as seen here: https://github.com/tgstation/tgstation/blob/c30d07f55a1078b6463b56046884fbce9bac6959/code/__HELPERS/lists.dm

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +			cargopads.Add(src)
Please use the list helpers when accessing lists, `Add` is rather slow and there are better solutions as seen here: https://github.com/tgstation/tgstation/blob/c30d07f55a1078b6463b56046884fbce9bac6959/code/__HELPERS/lists.dm

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +		if (!cargopads.Find(src))
Please use the list helpers when accessing lists, `Find` is rather slow and there are better solutions as seen here: https://github.com/tgstation/tgstation/blob/c30d07f55a1078b6463b56046884fbce9bac6959/code/__HELPERS/lists.dm

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +		if (cargopads.Find(src))
Please use the list helpers when accessing lists, `Find` is rather slow and there are better solutions as seen here: https://github.com/tgstation/tgstation/blob/c30d07f55a1078b6463b56046884fbce9bac6959/code/__HELPERS/lists.dm

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +			cargopads.Remove(src)
Please use the list helpers when accessing lists, `Remove` is rather slow and there are better solutions as seen here: https://github.com/tgstation/tgstation/blob/c30d07f55a1078b6463b56046884fbce9bac6959/code/__HELPERS/lists.dm

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +		active = 0
`FALSE`

2017-02-17 09:47 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +		active = 1
`TRUE`

2017-02-17 09:49 UTC, McBawbaggings commented on code/modules/telesci/telepad.dm
> +	user << "There are [charges]/[maximum_charges] charge\s left."
This doesn't make sense? This is gonna be 0 to 1 charges left depending on the value.

2017-02-17 09:52 UTC, McBawbaggings commented on code/modules/telesci/telepad.dm
> +	user << "There are [charges]/[maximum_charges] charge\s left."
Unless you want this to be a percentage in which you should do the *100 and capping the amount of decimal places and putting a percent sign after the calculation.

2017-02-17 10:01 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +	if(do_after(user, 50, target=T, progress = 1))
`do_after` can be stacked and you only remove charges after `do_after` has finished, allowing the user to use the item more often

2017-02-17 10:03 UTC, Chnkr commented on code/modules/telesci/telepad.dm
>  	force = 10
why does this have a force of 10?

2017-02-17 10:03 UTC, Chnkr commented on code/modules/telesci/telepad.dm
>  	throwforce = 10
why does this have a throwforce of 10?

2017-02-17 10:06 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +	if (active == 1)
`if(active)`

2017-02-17 10:06 UTC, Chnkr commented on code/modules/telesci/telepad.dm
>  		anchored = 0
`= FALSE`

2017-02-17 10:08 UTC, Chnkr commented on code/game/machinery/recharger.dm
> +				using_power = 1
`TRUE`

2017-02-17 10:20 UTC, JamieH commented on code/modules/telesci/telepad.dm
> +	user << "There are [charges]/[maximum_charges] charge\s left."
It's text, not math, so it says "1/10 charges left" or "4/10 charges left"

2017-02-17 10:20 UTC, JamieH commented on code/modules/telesci/telepad.dm
>  	force = 10
fixed

2017-02-17 10:20 UTC, JamieH commented on code/game/machinery/recharger.dm
> +				using_power = 1
The whole proc uses 1s and 0s, it'll just look weird.

2017-02-17 10:39 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +/obj/machinery/telepad_cargo/New()
/tg/ added initialize for station objects, mind taking a look if that might apply here?

2017-02-17 10:42 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +	if (name == "cargo telepad")
`if == initial(src.name)`

2017-02-17 10:42 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +/obj/machinery/telepad_cargo/attack_hand(mob/living/user)
add a do_after in this proc to prevent players from crashing the server

2017-02-17 10:43 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +/obj/machinery/telepad_cargo/attack_hand(mob/living/user)
or just a `CHECK_TICK` really, list operations in BYOND are terrible

2017-02-17 10:57 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +	if(do_after(user, 20*W.toolspeed, target = src, unique=TRUE))
attack_hand has no toolspeed

2017-02-17 10:57 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +	if(do_after(user, 20*W.toolspeed, target = src, unique=TRUE))
also the do_after is not needed since we have logging, and it's shit to do a do_after for something so simple

2017-02-17 12:27 UTC, banthebantz commented
Hell yes

2017-02-17 12:37 UTC, Chnkr commented on code/modules/telesci/telepad.dm
> +	if(do_after(user, 5, target = src))
needs a visible message

2017-02-17 14:53 UTC, tortellinitony commented
We have MULEbots for a reason, come on

2017-02-17 15:03 UTC, Chnkr commented
@tortellinitony mulebots are slow, maybe we should allow RD to upgrade mulebots?

2017-02-17 19:38 UTC, McBawbaggings commented on code/modules/telesci/telepad.dm
> +	user << "There are [charges]/[maximum_charges] charge\s left."
OH, sorry, I thought the whole expression was wrapped in square brackets, my bad.

2017-02-17 21:06 UTC, tortellinitony commented
there's literally a turbo speed wire @Chnkr

2017-02-18 02:26 UTC, cacogen commented
so they can be recharged? does cargo get a recharger though, or will they just be breaking into the cargo checkpoint?

2017-02-18 03:17 UTC, tortellinitony approved these changes

2017-02-18 03:17 UTC, merged