Vending Machine Overhaul
HippieStationArchive/HippieStation13-2 pull request #327
Opened 2017-02-22 06:57 UTC by tortellinitony

:cl: Tortellini Tony
add: Ported vending machines to tgui.
imgadd: New vending machine icons.
/:cl:

https://vgy.me/0VLo0Q.png

2017-02-22 21:35 UTC, KittyKathy commented
Can we still get our items super fast or is there a delay between each time it hands out a item? what about that old trick where you attach a wire to a coin and can have a chance for the machine to not eat the coin, is that still in? Looks pretty good.

2017-02-23 05:49 UTC, tortellinitony commented
You can still do the coin thing, and yes there is a delay between vending, it should be about a second

2017-02-23 06:15 UTC, cacogen commented
those look like goon sprites

which isn't a bad thing

2017-02-23 07:16 UTC, tortellinitony commented
I took danno's and added a goon-like roof to them since they looked flat before

2017-02-23 08:31 UTC, JohnGinnane commented on tgui/src/interfaces/vending.ract
> +<ui-display title='Products'>
This is tgui? Noice

2017-02-23 09:56 UTC, ghost requested changes
Code and Sprites look fine, please make sure you use istypeless loops and use the list helpers 👍

2017-02-23 09:56 UTC, Chnkr commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/ui_data()
This proc needs to use the lazy helpers

Please do not initialize lists directly on the object, or in `/new` please use the `LAZY_` list helpers when working with lists.

More about that can be found [here](https://github.com/HippieStation/HippieStation13/blob/master/code/__HELPERS/lists.dm#L459)

and

Please use _istypeless for loops_ you can find more information about this in the [contributing.md](https://github.com/HippieStation/HippieStation13/blob/master/CONTRIBUTING.md)

2017-02-23 15:18 UTC, ghost approved these changes

2017-02-23 15:19 UTC, merged