Ports nearcrit
HippieStationArchive/HippieStation13-2 pull request #334
Opened 2017-02-23 06:59 UTC by tortellinitony

:cl: Tortellini Tony
add: Ported nearcrit.
/:cl:

It works, what more can I say?

2017-02-23 08:47 UTC, JohnGinnane commented on tgstation.dme
> +#include "code\game\sound.dm"
What's up with these changes ?

2017-02-23 09:08 UTC, JohnGinnane requested changes
Absolute legend but don't forget about using whisper to suicide in near crit

2017-02-23 09:47 UTC, Chnkr commented on tgstation.dme
> +#include "code\game\sound.dm"
That is BYOND re-shuffling the DME it's fine

2017-02-23 09:50 UTC, Chnkr commented on code/modules/mob/mob.dm
> +	canmove = !((is_nearcrit(src) ? 0 : ko) || resting || stunned || chokehold || buckled || (!has_legs && !ignore_legs && !has_arms))
`ko` is a dumb variable that basically determines if you are KO on the floor or not, nearcrit should overwrite that

2017-02-23 10:00 UTC, JohnGinnane commented on code/modules/mob/mob.dm
> +	canmove = !((is_nearcrit(src) ? 0 : ko) || resting || stunned || chokehold || buckled || (!has_legs && !ignore_legs && !has_arms))
Yes but the issue is `ko` is made up of `weakened || paralysis || stat || (status_flags & FAKEDEATH)`

As it is now it seems like going from health>0 to -50<health<0 means that even if you were unconscious, paralysed or weakened then you can still move...

2017-02-23 14:34 UTC, JohnGinnane approved these changes
Tony did some testing on the paralysis and it's working correctly, everything else looks good so let's go!

2017-02-23 14:34 UTC, merged

2017-02-24 17:28 UTC, Carbonhell commented on code/modules/mob/mob.dm
> +/proc/is_nearcrit(mob/living/M)
Why make this a global proc instead of a libing proc...?