Removes the singularity scare hallucination
HippieStationArchive/HippieStation13-2 pull request #352
Opened 2017-02-24 22:34 UTC by onein50million

:cl: Spyridon10
fix: Removes the singularity hallucination, as it was causing crashes.
/:cl:

I couldn't figure out why, but for some reason the singularity scare hallucination occasionally crashes Dream Seeker. 
fixes #348 
fixes #181

2017-02-24 22:59 UTC, ghost submitted a review, later dismissed

2017-02-24 22:59 UTC, Chnkr commented on code/modules/flufftext/Hallucination.dm
> +//Singularity scare causes crashes for some reason
don't comment this out, just remove it from the `major` list

2017-02-24 23:00 UTC, tortellinitony requested changes

2017-02-24 23:00 UTC, tortellinitony commented on code/modules/flufftext/Hallucination.dm
> +/obj/effect/hallucination/simple/
Why add this?

2017-02-24 23:01 UTC, tortellinitony requested changes

2017-02-24 23:01 UTC, tortellinitony commented on code/modules/flufftext/Hallucination.dm
> +//		if("singulo")
Delete this instead of commenting it out

2017-02-24 23:05 UTC, Chnkr commented on code/modules/flufftext/Hallucination.dm
> +//		if("singulo")
Just remove it from the `major` list

2017-02-24 23:09 UTC, onein50million commented on code/modules/flufftext/Hallucination.dm
> +/obj/effect/hallucination/simple/
I must have deleted that by accident. I'll fix it

2017-02-25 21:20 UTC, tortellinitony approved these changes
Looks good

2017-02-25 21:21 UTC, merged

2017-02-27 18:47 UTC, banthebantz commented
we should probably fix this or replace it with something else at some point, hell maybe even a hallucination overhaul