Chainsaw2
HippieStationArchive/HippieStation13-2 pull request #394
Opened 2017-03-04 01:28 UTC by Jaygriff

:cl: Jaygriff
soundadd: Add sounds for chainsaw startup
/:cl:

[]: # Per #336

2017-03-04 22:32 UTC, JohnGinnane requested changes

2017-03-04 22:32 UTC, JohnGinnane commented on code/game/objects/items/weapons/twohanded.dm
> +	if(on)
This isn't necessary as the wield() proc already does this

2017-03-05 19:57 UTC, Jaygriff reviewed
We only want the sound to play when the chainsaw is turned on. Chainsaw cannot be unwielded as it is a forced two handed weapon. Doesnt use default wield and unwield procs because of this.

2017-03-05 20:04 UTC, JohnGinnane commented
Oh right, chainsaw doesn't use wield/unwield. Did you test that it works like that?

2017-03-05 20:05 UTC, Jaygriff commented
Yep. Just plays the sound when the chainsaw is toggled on. I do not recall us having a sound for it turning off and I couldn't find it in the files if we did.

2017-03-05 20:07 UTC, JohnGinnane approved these changes

2017-03-05 20:07 UTC, JohnGinnane commented
I don't either, cool

2017-03-05 20:07 UTC, merged