Comments out all those nasty anti-stuns like we had pre-rebase.
HippieStationArchive/HippieStation13-2 pull request #463
Opened 2017-03-14 16:36 UTC by GuyonBroadway

We removed these pre-rebase, no reason not to do so now. 

:cl: Guyonbroadway
del: Removed the recipes for Meth and Ephedrine
del: Removed the ling adrenals evolution
del: Removed Adrenal implants from the traitor uplink
del: Removed Stimpacks from the traitor
del: Removed adrenal implants from the R&D protolathe
tweak: Unholy water no longer reduces stun times
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)

2017-03-14 16:38 UTC, banthebantz commented
jenkins kill

2017-03-14 16:43 UTC, GuyonBroadway commented
I think I see the problem.

2017-03-14 16:56 UTC, GuyonBroadway commented
Jenkins Unkill

2017-03-14 18:49 UTC, Sarcalogo commented
Good work.

2017-03-14 20:00 UTC, trifornt-tinfornt commented
This is something that should have never been returned. Alas, rushed rebase.
Can't wait to see all of the people once again defending them, saying that they're "fine" even though they're a hard counter to the entire shitty combat system that is spam stuns then cuff.
Remove the shitty hugbox items that were designed around a completely different playerbase that has admins that restrict murderboning and powergaming to begin with, then we can remove the crappy balance in stuns - hopefully.

Merge this. They make the entire game about them, which is not good design.

2017-03-14 20:08 UTC, banthebantz commented
dem anti stuns are nastay shit boi

2017-03-14 20:18 UTC, Chnkr commented
no, this is **bad**

2017-03-14 20:20 UTC, ghost requested changes
I personally don't agree with any of this, but the playerbase seems to want it.

I'd personally recommend keeping all the chems, and just making them harder to use, more brain damage, more toxins, chances for a heart attack and the such

2017-03-14 20:20 UTC, Chnkr commented on code/game/gamemodes/changeling/powers/adrenaline.dm
> +/*
**DO NOT COMMENT THINGS OUT.**

**REMOVE IT.**
**OR IMPROVE IT.**

2017-03-14 20:20 UTC, Chnkr commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	//M.AdjustParalysis(-1, 0)
**DO NOT COMMENT THINGS OUT.**

**REMOVE IT.**
**OR IMPROVE IT.**

2017-03-14 20:20 UTC, Chnkr commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	//M.AdjustWeakened(-1, 0)
**DO NOT COMMENT THINGS OUT.**

**REMOVE IT.**
**OR IMPROVE IT.**

2017-03-14 20:20 UTC, Chnkr commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	//M.AdjustStunned(-1, 0)
**DO NOT COMMENT THINGS OUT.**

**REMOVE IT.**
**OR IMPROVE IT.**

2017-03-14 20:20 UTC, Chnkr commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		//M.AdjustWeakened(-2, 0)
**DO NOT COMMENT THINGS OUT.**

**REMOVE IT.**
**OR IMPROVE IT.**

2017-03-14 20:20 UTC, Chnkr commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		//M.AdjustStunned(-2, 0)
**DO NOT COMMENT THINGS OUT.**

**REMOVE IT.**
**OR IMPROVE IT.**

2017-03-14 20:20 UTC, Chnkr commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		//M.AdjustParalysis(-1, 0)
**DO NOT COMMENT THINGS OUT.**

**REMOVE IT.**
**OR IMPROVE IT.**

2017-03-14 20:20 UTC, Chnkr commented on code/modules/reagents/chemistry/recipes/drugs.dm
> +/*
**DO NOT COMMENT THINGS OUT.**

**REMOVE IT.**
**OR IMPROVE IT.**

2017-03-14 20:20 UTC, Chnkr commented on code/modules/reagents/chemistry/recipes/medicine.dm
> +/*
**DO NOT COMMENT THINGS OUT.**

**REMOVE IT.**
**OR IMPROVE IT.**

2017-03-14 20:20 UTC, Chnkr commented on code/modules/research/designs/medical_designs.dm
> +/*
**DO NOT COMMENT THINGS OUT.**

**REMOVE IT.**
**OR IMPROVE IT.**

2017-03-14 20:20 UTC, Chnkr commented on code/modules/uplink/uplink_item.dm
> +/*
**DO NOT COMMENT THINGS OUT.**

**REMOVE IT.**
**OR IMPROVE IT.**

2017-03-14 20:20 UTC, Chnkr commented on code/modules/uplink/uplink_item.dm
> +/*
**DO NOT COMMENT THINGS OUT.**

**REMOVE IT.**
**OR IMPROVE IT.**

2017-03-14 21:39 UTC, ghost requested changes

2017-03-14 21:39 UTC, Chnkr commented on code/game/gamemodes/changeling/powers/adrenaline.dm
> +//Nothing to see here
This is still bad, remove the file, remove it from the `.dme`

2017-03-14 21:55 UTC, McBawbaggings commented
![kellyhandicapparking_jpg_630x1200_upscale_q85](https://cloud.githubusercontent.com/assets/15840795/23924023/fb44555a-0900-11e7-981f-c9f1ed9b2f5e.jpg)
+1

2017-03-14 22:00 UTC, McBawbaggings commented
Actually, you'd be better off making sure each chemical you removed is no longer referenced via chemid in the code. It currently does not fulfill this.

2017-03-14 22:02 UTC, McBawbaggings commented
https://github.com/HippieStation/HippieStation13/search?utf8=%E2%9C%93&q=ephedrine
https://github.com/HippieStation/HippieStation13/search?utf8=%E2%9C%93&q=methamphetamine
https://github.com/HippieStation/HippieStation13/search?utf8=%E2%9C%93&q=changelingAdrenaline
https://github.com/HippieStation/HippieStation13/search?utf8=%E2%9C%93&q=changelingAdrenaline2

2017-03-14 23:51 UTC, PopNotes commented
Please god don't fucking remove ling adrenals

2017-03-14 23:52 UTC, PopNotes commented
And _how_ are stimpacks so much of a problem they need to be outright removed?

2017-03-15 00:06 UTC, trifornt-tinfornt commented
It's because antistuns are a bad idea to begin with.
Changelings are OP and boring, they don't fit Hippie at all. Sure, they aren't as OP as they were before but they're still really lame. Free antistuns for anyone is a terrible idea.
They need to be removed because they're a hard counter to 90% of combat. It's not like they have a counter themselves, either.
They were removed last rebase and the game was better for it. Now they're back because rushed rebase.
They shall be removed again and nobody will miss them except for the players who used them as a crutch to get out of their poor situations.

2017-03-15 02:33 UTC, KittyKathy commented
So this is a botany buff? I mean I like botany and all that but giving them the only way to get antistuns as nonantag that isn't crappy bathsalts is pretty bad. This easy solution is not the one because you just removed the recipe for some of the chemicals and only really fixed nicotine and unholy water. 

Omega Weed the plant contains Crank and Meth, Ambrosia deus and Tea astra contains synaptizine, and Coffee robusta contains ephedrine. This also does not account for the fact that strange plants can contain I think any synthetically made chemical as I once got meth trait from one.

There are probably other ways to get these chemicals that tg added like borers that can make meth in their hosts. The best solution you could have done as a first step would probably be to JUST ONLY delete the part of the code where the chemical/implant/ability calls adjuststuns()/adjustweaken()/adjustParalysis() so they still exist as speed boosters and healing chemicals in the case of stimulants(the chemical). You know like what you did with nicotine and unholy water.

The adrenaline implant was pretty useful for the omnizine it gave which could have saved you in light crit and also the ability to increase speed at will.

The only thing the "players" complained about was that it removed stuns so maybe that is the only thing that should be removed from the antistuns.

2017-03-15 04:16 UTC, trifornt-tinfornt commented
Drugs that just increased speed with some downsides (like jittery movement/double stun time like Kierany's heroin idea) would be fine. It'd be lame and easily abused in the long run, I could guarantee it. Remember hyperzine?
Botany could probably get some changes in the future and to be honest Botany is pretty OP in their own right.
I disagree with antistuns at their core, everyone hates them except for the people who powergame every round and use them. Even then I've seen some powergamers criticize antistuns. So it's not like the people who hate antistuns are so small that they should be put in quotations.
I do think that traitors should get some kind of edge to keep them going in fights, but that's what all of those trinkets and gadgets are for. If you get stunned, tough shit. That's SS13. Maybe a healing implant with omnizine would be nice for if they didn't finish you off, but that's it.
Other than that, drugs like meth should not make you gods. They should function like Space Drugs and be a joke chem or even a kill chem.

2017-03-15 13:34 UTC, Sarcalogo commented
Wew lad. If only the old repo wasn't deleted, I would have screenshot what Kitty Kathy said to me when I did the exact same thing this guy did. Freaked out and told me stuff like "You never listen" "You don't know what you are doing." "You left shit out YOU FUCK EVERYTHING UP!" "LET ME DO IT INSTEAD" 

Comical.

2017-03-15 17:50 UTC, Thelolswat commented
The fact that a chemist can get a crap ton of 9u meth patches, and a stunbaton, can control the entire station because there is no way to put them down unless you have godlike aim with a disabler is shitty.

Should keep the antistun part, but add extremely debilitating effects (like random heart attacks, a very long stun once it wears off, taking toxin damage, dropping items, hitting yourself with items).

2017-03-15 17:52 UTC, banthebantz commented
While removing them is the easiest thing to do, I am also still of the crowd that believes they can be improved or at least re-purposed rather than completely removed.

2017-03-15 18:17 UTC, Sarcalogo commented
Nobody cares you faggot, these need to be removed and it is literally just a port of a feature that was present before the rebase.

2017-03-15 18:49 UTC, banthebantz commented
I don't disagree with you there, I just also agree with the sentiment that these drugs could return with a different function as opposed to being gone forever.

2017-03-15 18:54 UTC, trifornt-tinfornt commented
There are few times I agree with Sarca.
This is one of them.
I also agree that the drugs could probably be repurposed into something else, personally I think they should just be different versions of Space Drugs - perhaps more intensive so you could use them as floor pill or even smoke to distract and weaken crowds.

2017-03-15 19:03 UTC, banthebantz commented
...That is what I'm suggesting

2017-03-15 23:13 UTC, Chnkr commented
I agree with @banthebantz here

2017-03-16 00:12 UTC, trifornt-tinfornt commented
Yeah. We should bring them back in the future as forms of Space Drugs or something.
But for now we gotta kill 'em.

2017-03-16 15:36 UTC, GuyonBroadway commented
Figured out a better way to nerf the fuck out of anti-stuns, going to make a new PR on it.

2017-03-16 15:36 UTC, closed without merging

2017-03-16 18:38 UTC, trifornt-tinfornt commented
Nerfing antistuns instead of removing them.
Welp. Here we go again with the dumb Kierany shit that didn't work.

2017-03-16 18:41 UTC, banthebantz commented
JUST MAKE THEM A MEME

2017-03-16 19:01 UTC, trifornt-tinfornt commented
HOLY SHIT JUST MAKE THEM A MEME

2017-03-16 19:28 UTC, banthebantz commented
AN EVEN GREATER MEME

2017-03-16 20:24 UTC, trifornt-tinfornt commented
A MEME SO GREAT THAT THE SERVER CAN'T HANDLE IT

2017-03-16 21:02 UTC, Sarcalogo commented
I change my mind, you did a a terrible job. How many times do we need to try "new" anti-stun systems? The whole concept is fucking busted, how many times do we have to state this. I'll make it simple for you to understand.

\>People complain about anti-stuns
\>Someone tries to remove them
\>A bunch of coders who have never played the game, and idiots who have scarcely played the game a few months come along
\>NO, NO, IT'S REMOVING. WE SHOULD RE-TOOL. STUNS ARE TOO POWERFUL!! THEY NEED A COUNTER!!
\>"Nerf" anti stuns
\>Doesn't do shit because it's still at it's core a FUCKING ANTI-STUN YOU IDIOTS. THAT'S THE PROBLEM. THE PROBLEM IS THAT IT REMOVES STUNS.
\>Idiot coders wipe a bead of sweat off their forehead
\>"Phew... another fine job by me, the problem is solved!'
\>People still go around abusing anti-stuns ruining the entire balance of the game
\>Powergamers find a way to mitigate "nerf" with almost no effort
\>Continue to do so
\>Months later, as the idiots catch on, people complain about anti-stuns
\>The cycle repeats until it is somehow broken

  YEARS AND YEARS AGO I wrote ten page essays about this shit on 4chan's /vg/. Why? Why do people keep making the same mistakes?

2017-03-16 21:27 UTC, MethMedic commented
JUST REMOVE THEM. We TRIER nerfing them before and they found a way around it. The only nerf that would be acceptable is an extremely fast metabolic rate, extremely low OD level (5u) and effects that are so bad it's not even worth it. Seizures, brain damage, toxin damage, random overheating, and possible heart attacks. You can't just have one or two of those as they can mix them with chems that stop them. Make it have so many bad side effects that to counter them all, you'd need an insane amount of other chems

2017-03-16 22:24 UTC, cacogen commented
I did not read any of the comments here except the last one.

However, ODs and fucking you up is a shitty way to nerf anything. Either make the effect less (e.g. less of a speed boost, less of a stun reduction) or make it last less time. Still preferential to not having it, but not the complete and utter bullshit we have currently.

Personally I've never had any problem with antistuns, but that's probably because I've never had them used against me. I've only ever made omega weed as a botanist and given it all the good shit like ephedrine from coffee robusta and bicaridine, kelotane and omnizine from ambrosia and run around the station pushing people the length of entire hallways in the space of a second.

2017-03-16 22:31 UTC, JohnMcLaime commented
Just remove stuns,

2017-03-16 22:58 UTC, MethMedic commented
Either nerf them so hard they are pointless or remove them. Make stuns stamina based. Bam it's fixed. Took me 5 seconds.

2017-03-16 23:25 UTC, Sarcalogo commented
\>Remove stuns
\>Make stuns stamina based
I can't tell what is stupider. Removing stuns or defending anti-stuns.

2017-03-18 06:38 UTC, Swagile commented
we nerfed the shit out of one anti stun

ander found a way to use several chems together to negate the bad effects of an even better anti stun

rinse and repeat until mcbawg put his foot down and completely removed anti stuns

everyone was happy, no meme anti-stuns were added, people moved on

we don't fucking need to nerf anti stuns, we just need to remove them