Anti stuns re-work (and mostly a removal)
HippieStationArchive/HippieStation13-2 pull request #467
Opened 2017-03-16 23:38 UTC by GuyonBroadway

Only two true anti-stun chems exist now, meth and bath salts and they now come with significant downsides. 

Rather than remove all these chems I changed them, except for lingdrenals. those can fuck off. Lings can make anti-stun chems too and have a purge chems button for when they start to hurt you. 

All anti-stun chems have either had their anti-stun effects removed or given considerable downsides. 

:cl: Guyonbroadway
del: Changeling adrenals are fukken gone.
del: Adrenal implants are also removed...
add: However adrenal implants have been replaced with the Combat Stimulant Implant, instantly heals an amount of most types of damage in addition to curing blindness and deafness as well as giving you a potent cocktail of healing drugs. 
tweak: Nicotine no longer reduces stuns
tweak: Meth no longer makes you run fast, it also steadily causes a build-up of histamine in your system. If you get stunned it causes a spike of histamine and some meth will be removed from your system.
tweak: Ephedrine no longer reduces stuns and will make you hungry while draining nutriment and vitamin from your system.
add: If you have Meth and Ephedrine in your system they will react violently and you will catch fire that gets more intense the longer it goes on.
tweak: Unholy water no longer reduces stuns, but it's healing has been boosted a bit and will also heal clone, brain and bloodloss damage.
tweak: Bath salts will now fuck you up much more and cause you to drop items as long as it's in your system. 
/:cl:

2017-03-16 23:41 UTC, PopNotes commented
I love these changes as it unfucks antistuns the way they should be unfucked instead of just lazily removing them

my only complaint is that now nicotine is now a dummy chem with addiction if I'm not mistaken
blease give it some kind of neat feetchur and I'll give this all my approvals and cummies

2017-03-16 23:44 UTC, GuyonBroadway commented
It still provides stamina regen, later on I want to make each brand of cigarette have their own children of nicotine with minor benefits. but that's for another PR I feel.

2017-03-16 23:48 UTC, PopNotes commented
Last request, blease fix typos
this game has enough spelling errors as it is

2017-03-16 23:48 UTC, tortellinitony commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	description = "Increases movement speed but causes you to lose wieght fast, will also purge nutriment and vitamin from the body. Breaks do Overdose deals toxin damage and inhibits breathing."
Breaks do?

2017-03-16 23:48 UTC, tortellinitony commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			M.reagents.remove_reagent("methamphetamine", 5)
Have you tested if this can go negative?

2017-03-16 23:48 UTC, tortellinitony commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
>  	M.status_flags |= GOTTAGOFAST
Maybe make it gottagoreallyfast instead?

2017-03-16 23:49 UTC, McHatters commented
Good PR, lots better than some of the attempts we have made at addressing the stuns issue.

2017-03-16 23:50 UTC, PopNotes commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
>  	M.status_flags |= GOTTAGOFAST
gno

2017-03-16 23:50 UTC, GuyonBroadway commented
fixing typos, typos are my calling card.

2017-03-16 23:51 UTC, tortellinitony requested changes

2017-03-16 23:51 UTC, tortellinitony commented on code/game/objects/items/weapons/implants/implant_misc.dm
> +	desc = "A coctail of potent drugs will heal damage allowing you to fight for longer"
A cocktail of potent drugs that will heal damage, allowing you to fight for longer.

2017-03-16 23:51 UTC, tortellinitony commented on code/game/objects/items/weapons/implants/implant_misc.dm
> +	imp_in << "<span class='notice'>You feel the pain fade and your wounds close!!</span>"
You feel the pain fade, and your wounds close!

2017-03-16 23:51 UTC, tortellinitony commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	description = "Slightly increases stamina regenration If overdosed it will deal toxin and oxygen damage."
Slightly increases stamina regeneration. If overdosed, it will deal toxin and oxygen damage.

2017-03-16 23:53 UTC, McBawbaggings commented
![image](https://cloud.githubusercontent.com/assets/15840795/24023363/be5fd642-0aa3-11e7-8dc4-74ad17d9f2fb.png)
I'll have a look at the changes tomorrow lmao

2017-03-16 23:55 UTC, tortellinitony commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
>  	M.status_flags |= GOTTAGOFAST
This makes sense, considering it was removed from meth which keeps stamina regen, and this loses stamina regen.

2017-03-16 23:56 UTC, tortellinitony commented
I like these changes, and I think that they are much better than just removing the chemicals outright.

2017-03-16 23:58 UTC, GuyonBroadway commented
I want to make a combat capable replacement  replacement for lingdrenals and I have some ideas, but I will do those later.

2017-03-17 00:06 UTC, GuyonBroadway commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			M.reagents.remove_reagent("methamphetamine", 5)
Working on that, might be the cause of a runtime I saw (and I thought I fixed)

2017-03-17 00:11 UTC, GuyonBroadway commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			M.reagents.remove_reagent("methamphetamine", 5)
Ahaha, it does runtime, gotta fix that...

2017-03-17 00:19 UTC, GuyonBroadway commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			M.reagents.remove_reagent("methamphetamine", 5)
Ok better idea, up the metabolic rate by default.

2017-03-17 00:25 UTC, GuyonBroadway commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
>  	M.status_flags |= GOTTAGOFAST
your are faster than literal bullets as is, no need to make it any more insane

2017-03-17 00:28 UTC, trifornt-tinfornt commented
Okay.
Antistuns are still a terrible idea. I like the fact that you've replaced the adrenals implant with a healing implant though, as well as making ephedrine give you negative effects for constantly trying to run fast.

But meth? Nah. Sorry man but small histamine injections for instantly getting up and being able to bring the fight back again, as well as with current riot shields and etc. is a terrible idea. You have chems that can flush Histamine out of the system, so they'll just apply those patches for when they do get stunned and guarantee an instawin. Even then, Histamine is weak drug that requires overdosing to do anything efficient - and 10 units per stun seems to not fit that threshold. Meth is far too easy to spam and churn out and this will just make them churn out anti-histamine alongside it - just like how they churn out mannitol to counter the brain damage. Bad nerf of a bad idea. Stop.
Kierany tried to nerf meth and other chems and failed. Please stop trying to nerf a system that breaks the entire, already flawed combat system of a game and instead decide "hey maybe we should remove this because it's boring and stupid". We did this last rebase and it was for the better. Make meth some kind of space drugs clone that fucks you up.

Bath Salts basically being a meme "I can't stun you but you can't stun me watch me prance around like an idiot" sounds like it could still be exploited by powergamers, but otherwise it's meh. Last I remember it turned you into a prancing idiot who could hardly walk straight anyhow, you pretty much just ran in circles.

Would still rather have them be stronger versions of space drugs.

2017-03-17 00:49 UTC, PopNotes commented
Now that typos and whatnot have been fixed, I wholeheartedly endorse this PR.
Trifornt can bitch about this when he fixes stuns.

2017-03-17 00:49 UTC, trifornt-tinfornt commented
bitch bitch whine whine cry cry
muh balunce

2017-03-17 00:54 UTC, McHatters commented
Trifornt does sound like he's got a point regarding histamine. I forgot that we got a chem (Diphenhydramine) that deals specifically with histamine overdose, and a chemist can easily whip it up to make Meth a drawback-free anti-stun again.

2017-03-17 00:58 UTC, trifornt-tinfornt commented
Actually no matter what unless you use some OP chem it'll be easily negated by other chems that powergamers and "robust"-cripples/autists can whip up in seconds. It's a bad idea to make meth the exact same except it hurts you when you get stunned or if you have it in your system for extended periods of time.
It's a bad idea to fix an idea that was so bad it got removed.

2017-03-17 01:04 UTC, PopNotes commented
"it got removed therefore it should be removed again NO QUESTION DO NOT PROPOSE DIFFERENT IDEAS" is a bad meme

The fact that meth no longer has a speed boost is exactly what it needed in the first place, histamine is just there to make spamming it more of a bitch

2017-03-17 01:09 UTC, trifornt-tinfornt commented
Hate to break it to you but we've seen Ephedrine and other antistun chems before without movement buffs still be horrendously overpowered in the past. Nothing anyone tried to fix this worked, there were either easy fixes to it or it actually ended up BUFFING them in the long run. The sheer fact that you can get up faster after being stunned (which is 90% of the combat system) is more than enough to completely bust something, as now you have time to run away and return fire with whatever weapon you have to stun THEM. If they don't have antistuns, they're dead, GG.
When you have an item that makes the entire game about you, and if they don't have X then they're as good as fucked, then you've balanced something terribly wrong. This is why the Reactive Teleport Armor, Riot Shields, and stuns themselves are bad (although disarm intent is a godsend for stuns) and not just these things.
But these are perhaps the worst of the offenders.

2017-03-17 01:11 UTC, PopNotes commented
when did neb get here exactly

2017-03-17 01:12 UTC, trifornt-tinfornt commented
Neb said "X is a bad meme" when he saw an argument he didn't like. I saw him do it like 3 times, unless that was Nokington.

2017-03-17 01:14 UTC, PopNotes commented
I've said that shit for awhile and had no idea I was channeling anyone

Regardless, the idea of completely removing antistuns while changing NOTHING about stuns is a terrible meme and should not be repeated, even if the changes don't do much to fix the problem at least they're doing something other than **outright removing content from the game**

2017-03-17 01:15 UTC, trifornt-tinfornt commented
I agree. Outright removing content is bad. That's why I say change them to space drugs except with the potential to be an actual killchem or something like cryptobiolin. However seeing that nobody here can quite see that trying to balance these things is impossible it's best to just get them removed them have them re-added when someone can make them a wacky chem instead of one that dictates the entire flow of the game's combat system.

2017-03-17 02:02 UTC, trifornt-tinfornt commented
Awesome, now you can't abuse it with diphenhydramine.
What does histamine do again? Has a chance to make you take brute damage?
Well how about I just use this lovely chem that heals up that brute damage really fast and is easy to make, like Styptic Powder!
Sucks for you!

2017-03-17 03:02 UTC, ghost requested changes

2017-03-17 03:02 UTC, Chnkr commented on code/game/gamemodes/changeling/powers/adrenaline.dm
> +//better ability pending
bad

2017-03-17 03:14 UTC, GuyonBroadway commented on code/game/gamemodes/changeling/powers/adrenaline.dm
> +//better ability pending
Deleting the file causes jenkins to flip the fuck out and I'm not sure how to fix that.

2017-03-17 04:23 UTC, tortellinitony requested changes

2017-03-17 04:23 UTC, tortellinitony commented on tgstation.dme
> +#include "code\game\sound.dm"
Sneaky

2017-03-17 04:24 UTC, GuyonBroadway commented on tgstation.dme
> +#include "code\game\sound.dm"
Genuinely not intentional, i must've fucked up my repo and that was stuck in there. Will fix tomorrow.

2017-03-17 05:43 UTC, MethMedic commented
The histamine will do nothing. Powergamers will just add antihistamine to their patches. Bam, look I found a loophole. Meth should be removed, but since you don't wanna do that we gotta compromise. Meth should fuck you up BAD but make it so you get away alive. Alive but fucked up bad. You shouldn't be able to fight while on it, only escape. And using it should be so debilitating that it should be used only in a life or death situation.

2017-03-17 08:41 UTC, Pyko1 commented
```
/obj/item/clothing/suit/armor/abductor/vest/ui_action_click()
	switch(mode)
		if(VEST_COMBAT)
			Adrenaline()
		if(VEST_STEALTH)
			if(stealth_active)
				DeactivateStealth()
			else
				ActivateStealth()

/obj/item/clothing/suit/armor/abductor/vest/proc/Adrenaline()
	if(ishuman(loc))
		if(combat_cooldown != initial(combat_cooldown))
			loc << "<span class='warning'>Combat injection is still recharging.</span>"
			return
		var/mob/living/carbon/human/M = loc
		M.adjustStaminaLoss(-75)
		M.SetParalysis(0)
		M.SetStunned(0)
		M.SetWeakened(0)
		combat_cooldown = 0
		START_PROCESSING(SSobj, src)
```

There is still this left, but then again it hasn't ever been an issue tho.

2017-03-17 08:42 UTC, Pyko1 commented
How about meth has a chance to blow up on mixing, like those ghetto meth labs?

2017-03-17 09:33 UTC, Chnkr commented on code/game/gamemodes/changeling/powers/adrenaline.dm
> +//better ability pending
remove the file from the DME

2017-03-17 12:51 UTC, GuyonBroadway commented
@MethMedic The only antihistamine in the game has been accounted for. It will make using meth safer but combat impossible.

2017-03-17 15:37 UTC, trifornt-tinfornt commented
Doesn't matter, Histamine is easily counterable without the anti-histamine drug. All it does is give you brute damage. Slap on a brute patch, bam. You're fine. You can still use meth to powergame.
As I said, bad idea for a bad idea that was so bad it got removed.

2017-03-17 16:10 UTC, banthebantz commented
Do you overdose on the histamine or what? Histamine OD is super lethal but otherwise it's just annoying eye damage and brute.



_Just merge Arc-Luminol and have it give them that instead, they'll never touch meth again._

2017-03-17 17:12 UTC, GuyonBroadway commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			M.reagents.add_reagent("skewium", rand(1,5))
@trifornt-tinfornt May i direct your attention here?

Go ahead! Use Anti-histamine and meth at the same time, I DARE YOU!

2017-03-17 17:22 UTC, Chnkr commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			M.reagents.add_reagent("skewium", rand(1,5))
Thanks for adding an easier recipe for skewium

2017-03-17 18:45 UTC, GuyonBroadway commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			M.reagents.add_reagent("skewium", rand(1,5))
it has to mix IN a mob so i think the effort applied resonable. 

Plus making meth and Diphendramine together his about the same amount of effort.

2017-03-17 21:56 UTC, trifornt-tinfornt commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			M.reagents.add_reagent("skewium", rand(1,5))
@GuyonBroadway May I direct your attention to every single other brute and tox damage negating chem, which this doesn't currently stop people from using?
Brute patches ahoy!

2017-03-17 22:09 UTC, banthebantz commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			M.reagents.add_reagent("skewium", rand(1,5))
_Just merge Arc-Luminol and have it give them that instead, they'll never touch meth again._

2017-03-17 22:58 UTC, Sarcalogo commented
Nothing you ever do will change a thing. People will always find a way around whatever nerfs you add to anti-stuns, unless it outright instantly kills someone. So long as the anti-stuns are actually anti-stuns, then people will always use them. But go ahead and be the 100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000^99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999th  person to try to institute an anti-stun system.

2017-03-18 05:10 UTC, GuyonBroadway commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			M.reagents.add_reagent("skewium", rand(1,5))
@trifornt-tinfornt they don't just get a hit of histamine once per stun. They get a hit of histamine and tox damage every tic they are stunned. Needless to say, if you get stunned twice you will probably die.

2017-03-18 10:52 UTC, KittyKathy commented
This is overall good but may need some tweaking in future PRs though as I can see stuff that may be abused.  You may want to look into re adding Meth explosion so it's harder to make meth without blowing yourself up as it was removed for a unknown reason in #7.
I still think anything that removes stuns should have that ability to remove stuns removed but lets see if this would deter people from using it all the time.
You did not really change anything with Crank though is this intended?
You also left in Stimpacks for 5 tc which gives 50 units of stimulants which is unaffected by this PR.

2017-03-18 23:29 UTC, trifornt-tinfornt commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			M.reagents.add_reagent("skewium", rand(1,5))
@GuyonBroadway 
Or you can just run, apply a brute patch which doesn't take much time to do, then rush back. Tox damage is also easy to deal with.
This is a terrible idea, dude.

2017-03-19 18:18 UTC, Sarcalogo commented
What the fuck? Did some asshurt faggot delete my github comment? Fucking tyrants.

2017-03-19 18:26 UTC, Sarcalogo commented
Wow, this Popnotes guy is a prime example of what I'm talking about. Adhering to the idea that content should not be removed from the game, EVER. Which is to say that there are no ideas that are fundamentally bad, and that anything that is added to the game should not ever be removed. Notice how he isn't actually addressing any of Trifornt's arguments, just falling back on the "IT'S REMOVING CONTENT! THEREFOR IT'S COMPLETELY BAD!!!" He doesn't actually try to defend this proposition, he just states it as if it is an a priori truth. Anti-stuns completely break the game. Completely and utterly break the game, the only way to stop them from breaking the game is to change their fundamental nature, to make them not act as an anti-stun. In order to do that, you have to remove them either in the literal sense, or remove the FUNCTIONALITY of the anti-stun which is functionally the same as removing them altogether. You should most definitely fix things that break the game. This breaks the game, and the only way to fix it is to remove it. Therefor, by contradiction alone, I have disproved your ridiculous presupposition that you need to NEVER REMOVE CONTENT.  There are obviously cases where it is necessary. 

How many rounds where one guy kills the entire station effortlessly do you need to experience for you to realize this?

2017-03-19 19:39 UTC, GuyonBroadway commented
My reasoning for using histamine is over time the build-up goes from minor annoyance to actual danger if you his the OD threshold which comes about faster if you get stunned. There are other things I could do with this, like teeny tiny amounts of heparin so after a while you are bleeding uncontrollably and need a transplant. 

Also stimpacks are now 50u of healing nanites. Which is actually insane, you could survive in a vacuum or some fires with that shit.

2017-03-19 19:42 UTC, Sarcalogo commented
It doesn't matter what you do, powergamer will find ways around whatever you do unless you make it hilariously stupid like injecting 50 units of venom in you as soon as you take the pill, at which point you may as well just remove it. Refuse to learn from history, once again. Go on, everyone, merge it. Look as all of your changes do nothing to solve the problem in the long term.

I can guarantee you if you told Kitty Kathy to try to find a way around this, she could do it within an hour.

2017-03-19 19:44 UTC, GuyonBroadway commented
I'm calling this a last chance saloon solution, if this does not work then I will concede the point that it is untenable and just make meth a drug you can use to trip balls. 

And make bath salts the only anti-stuns and that would fukken kill you.

2017-03-19 19:51 UTC, PopNotes commented
Maybe I'm fucking insane. Maybe I've gone completely psychotic for some reason. Maybe I've lost all cognitive function.

But let me put this out there, as the frantic ramblings of a madman.

_###Maybe it's okay for something to be strong._

2017-03-19 19:56 UTC, Sarcalogo commented
My advice is to read this thread about a week from now when I finish writing it if you actually want to understand the arguments against anti-stuns, as I'm going hardcore into detail.

https://hippiestation.com/threads/putting-the-biggest-memes-to-rest-warning-requires-reading-decent-iq.6285/

2017-03-20 16:13 UTC, GuyonBroadway commented
I fucked up my repo and had to do a thing, Closing PR and re-opening here. https://github.com/HippieStation/HippieStation13/pull/475

2017-03-20 16:13 UTC, closed without merging