Adds examine messages for clothing rating its armour values
HippieStationArchive/HippieStation13-2 pull request #86
Opened 2017-02-07 17:22 UTC by cacogen

:cl: Clothing armour ratings on examine
add: Added estimation of armour values of clothing on examination
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)
The game's needed something like this for years. No more needing to metagame and read the code to know the armour values of clothing.

2017-02-07 17:26 UTC, JohnGinnane commented
This is kinda neat

2017-02-07 17:46 UTC, Pyko1 commented
needs if clown/cluwne/braindamaged It has a Mimeamous/Honk'a'lessous/Honk'a'lotic amount of bonking/range honking/light donking/energy bonking/explobonking/flame'o'chunking/acid'o'dunking protection.

2017-02-07 21:21 UTC, Chnkr commented
This code makes me want to kill myself, have you ever heard about `switch()`

2017-02-07 21:27 UTC, Carbonhell commented
Switch(var)
    If(val1 to val5)
        Do shit for 1,2,3,4,5
    If(6,7,8)
        Do shit for 6,7,8

Pls fix ur code

2017-02-07 21:30 UTC, tortellinitony commented
make a proc to give that message

2017-02-07 21:47 UTC, JohnGinnane commented
I would say instead of copying the same code and changing a few words you can definitely make it a single proc where you pass in the damage type (e.g. "bio") and then you can set the unique word for it so you have "biohazard" as all of the strings are the same pretty much.

However my biggest issue is this means every player suddenly knows everything about all clothing and that kinda makes everyone somewhat powergamey. Why not make it so you pick the biggest protection (bullet for bullet proof armour for example) and have it say "This looks like it gives <some/lots of> protection against <type>". However only if the type is greater than 40 for example. If nothing is then have it say "It doesn't look like it would protect you against much".

Having a full list of all damage types and approximate protection is kinda.. weird but I wanna hear admins thoughts...

2017-02-07 23:12 UTC, tortellinitony commented
Even if this was simpler, I think it's a shit idea.

2017-02-07 23:27 UTC, McBawbaggings commented
Switch statements would be grand here.
Perhaps a for loop for armor type rather than blocks of switch statements?

2017-02-07 23:31 UTC, GuyonBroadway commented
As neat as this is it could just be done in a less powergamey fashion by making the actual object descriptions more descriptive.

Something as simple as "has some extra bullet resistant Kevlar" or "has ablative fibre woven in" "has impact resistant gel pockets"

While hippie is not an RP server you could still make descriptions more fluffy yet accurate and if people REALLY want to know the exact values they can just check the Github.

2017-02-08 01:20 UTC, Spacedong commented
i want hand-holders and powergamers to fucking leave

2017-02-08 03:26 UTC, KittyKathy commented
Would be neat if it was like how security/medical hud works when you examine someone a link pops up where you can click it to open up a window to show/show in chat the information you want instead of spamming chat with all this info like if I just wanted to read the description I would get all this other info I might not need or want.

2017-02-08 08:20 UTC, cacogen commented
This is as far as I got. It doesn't work.
```
	var/armor_strength_text
	switch(armor)
		if(0 to 25) 
			armor_strength_text = "<font color='red'>small</font>"
		if(25 to 50) 
			armor_strength_text = "<font color='orange'>moderate</font>"
		if(50 to 75) 
			armor_strength_text = "<font color='blue'>heavy</font>"
		if(75 to 100) 
			armor_strength_text = "<font color='green'>extremely heavy</font>"

	var/armor_type_text
		if(armor["melee"]) 
			armor_type_text = "<font color='red'>melee</font>"
		if(armor["bullet"]) 
			armor_type_text = "<font color='red'>ballistic</font>"
		if(armor["laser"]) 
			armor_type_text = "<font color='orange'>laser</font>"
		if(armor["energy"]) 
			armor_type_text = "<font color='blue'>energy</font>"
		if(armor["bomb"]) 
			armor_type_text = "<font color='red'>blast</font>"
		if(armor["bio"]) 
			armor_type_text = "<font color='green'>biohazard</font>"
		if(armor["rad"]) 
			armor_type_text = "<font color='green'>radiation</font>"
		if(armor["fire"]) 
			armor_type_text = "<font color='orange'>burn</font>"
		if(armor["acid"]) 
			armor_type_text = "<font color='orange'>acid</font>"
	
	user << "It has \a [armor_strength_text] amount of [armor_type_text] protection."
```

2017-02-08 08:34 UTC, JohnGinnane commented
In what way does it not work?

2017-02-08 08:35 UTC, JohnGinnane commented
Oh right your switch statement. When you do switch(value) it compares or against the cases. Let me try find example

2017-02-08 08:37 UTC, cacogen commented
armor_type_text doesn't get defined either, the message just shows up with two blank spots

2017-02-08 08:37 UTC, JohnGinnane commented
https://github.com/HippieStation/HippieStation13-rebase/blob/42915e2f0fc726df31f1cebd7f3206907862c391/code/modules/events/ion_storm.dm#L97

Your statement is trying to comparé the *list* armor to those numbers, you'll want to compare the element on the list, E.g. armor["melee"]

2017-02-08 08:38 UTC, JohnGinnane commented
Yeah you also indented after defining type text, why?

2017-02-08 08:39 UTC, cacogen commented
it was left over from a switch statement that was there

2017-02-08 08:47 UTC, JohnGinnane commented
If you go into the switch statement you'll want to keep everything at the same indentation

2017-02-08 08:55 UTC, cacogen commented
>you'll want to compare the element on the list, E.g. armor["melee"]

will that mean 9 different switch statements for the 9 different possible damage types? is there a shorter way to do it?

2017-02-08 09:00 UTC, JohnGinnane commented
Yeah you could write a proc which takes three arguments, the armor list, type (like "fire") and description ("burn") and then you can do

```
switch(armor[type])
    if(...)
        armor_type_text "...[description]..."
```

2017-02-08 09:01 UTC, JohnGinnane commented
Making it work if you wear science goggles is cool Idea though, otherwise I think show only the biggest protection

2017-02-08 10:49 UTC, cacogen commented
I think it would be better on secHUDs, seeing as security are the people who need to worry about that sort of thing. It's not really relevant to research.

2017-02-08 13:36 UTC, cacogen commented on code/modules/clothing/clothing.dm
> +			msg += "[list_clothing_armour(user, armor)]<BR>"
this shows up in the wrong place and i'm not sure how to fix it
![](https://puu.sh/tTMZ6/13e18cf627.png)

2017-02-08 14:06 UTC, JohnGinnane commented on code/modules/clothing/clothing.dm
> +			msg += "[list_clothing_armour(user, armor)]<BR>"
Because your proc prints directly to user rather than returning a string

2017-02-08 14:06 UTC, JohnGinnane commented on code/modules/clothing/clothing.dm
> +		user << "Its [damdesc] protection is [damquality]."
...See here

2017-02-08 20:23 UTC, cacogen commented on code/modules/clothing/clothing.dm
> +			msg += "[list_clothing_armour(user, armor)]<BR>"
yeah i tried returning but then it just printed a single damage type instead of all of them

2017-02-08 20:26 UTC, JohnGinnane commented on code/modules/clothing/clothing.dm
> +			msg += "[list_clothing_armour(user, armor)]<BR>"
Yeah because you're only returning one string

2017-02-08 22:56 UTC, KittyKathy commented
This is pretty good now 10/10. I assume this works on pretty much anything that can has armor values right? what about things that block/deflect attacks like shields/esword/ablative armor? It won't show the block/deflect chances of those things right because that is not related to armor values at all right? Maybe that will be your next pr.

2017-02-08 23:48 UTC, cacogen commented
No, it won't. Good idea though, I'd forgotten about those. I'd like to add that in a different PR if this gets approved.

2017-02-08 23:50 UTC, Dudeinyourbackyard commented
could be cool yeah, just do up your code and i'll be down

2017-02-09 00:06 UTC, JohnGinnane commented
I'll do another review in the morning

2017-02-09 05:08 UTC, JamieH commented
Honestly I still would much rather see this on science rather then security, It seems a little too powergamey to give to security. Being able to analyse the property of things is definitely more of a science thing then security.

2017-02-09 12:04 UTC, cacogen commented
What would they ever use it for?

I don't think it's powergamey to give people information about an object's stats, considering real powergamers will just look it up in the code anyway.

2017-02-09 12:13 UTC, JohnGinnane commented
It makes it trivial for people to scan everything they see and find the most common dangerous weapon around. You would think a toolbox or extinguisher would be pretty great but then suddenly you find something which does way more damage and still common throughout the station.

As for making it science only, it's not relevant to their job but it means it makes them more valuable (for non-scientists). SecHUD already shows you who's wanted and who's implanted, having this coupled with it makes them very powerful. By giving this to science goggles it means they'll be used more often and then people have to decide "sechud, medhud or sciencehud?"

2017-02-09 12:15 UTC, JohnGinnane commented
Code looks pretty good now. Presumably you've tested it?

2017-02-09 12:15 UTC, JohnGinnane approved these changes

2017-02-09 12:17 UTC, cacogen commented
This is only for armour. It's my other pull that gives weapon damages.

Yep, I tested it.

I just don't think it'll get used very often if it's on science goggles.  But I can change it to that if you want.

2017-02-09 12:23 UTC, JohnGinnane commented
Whoops, my bad I mixed the two things up. But I personally thing it would be more "suitable" for science goggles, effectively buffing them so they are more likely to get robbed and used. Getting your hands on a sechud requires you to be sec, break in or loot a sec officer, which isn't as easy as grabbing science goggles from science

2017-02-09 12:26 UTC, cacogen commented
Okay, I'll add it to science goggles.

2017-02-09 18:02 UTC, JohnGinnane commented
Okay just need head input

2017-02-09 18:41 UTC, JohnGinnane requested changes
Code looks pretty great now tbh, just a few things and I think we're ready

2017-02-09 18:41 UTC, JohnGinnane commented on code/game/objects/items.dm
> +				force_str += "[nil]"
Shouldn't these just be = rather than +=?

2017-02-09 18:41 UTC, JohnGinnane commented on code/game/objects/items.dm
> +		msg += "Armor:<BR>"
I think add `<BR>` at start if force || throwforce so Armor is on a new line

2017-02-09 18:41 UTC, JohnGinnane commented on code/game/objects/items.dm
> +					break
Should be continue? If the first armour type is 0 but second isnt you won't see second..

2017-02-09 18:41 UTC, JohnGinnane commented on code/modules/mob/mob_defines.dm
> +	var/robustness_scanner = 0 //For mobs with HUDSunglasses. Enable to see armour rating of clothing items.
Comment should be science goggles now no?

2017-02-09 19:32 UTC, tortellinitony commented
get rid of the colors, come on man

2017-02-09 19:34 UTC, cacogen commented
Colours make it easier to read. Like the health analyser. Lets you find at a glance the part of the text you want.

2017-02-09 19:35 UTC, cacogen commented on code/modules/mob/mob_defines.dm
> +	var/robustness_scanner = 0 //For mobs with HUDSunglasses. Enable to see armour rating of clothing items.
yep, i missed this

2017-02-09 19:35 UTC, cacogen commented on code/game/objects/items.dm
> +					break
thanks

2017-02-09 19:35 UTC, cacogen commented on code/game/objects/items.dm
> +				force_str += "[nil]"
yep

2017-02-09 19:42 UTC, tortellinitony commented
no it makes it worse to read

2017-02-09 19:54 UTC, JohnGinnane commented
I think the colours are ![image](https://cloud.githubusercontent.com/assets/3355198/22800512/89f5cadc-ef01-11e6-8b6e-c57d6afa5c43.png)

2017-02-09 20:05 UTC, cacogen commented
I ended up getting rid of the ones from the damage types (not the damage values) because they just didn't look right to me.

2017-02-10 07:34 UTC, JohnGinnane approved these changes
Code looks great

2017-02-10 09:55 UTC, merged